### ISSUE TITLE
Fretboard text should be dynamically generated.

### ISSUE THREAD

**Issue by progfolio** [vifon/fretboard.el#2]
Storing the fretboard's textual representation in a defcustom works for the simple case, but is inflexible.
Ideally the text would be generated from a number of other user options, which could be changed on the fly. e.g.

- Number of desired frets (or a specific range of frets)
- Number of strings
- Tuning of the instrument
- Scale to spell on the fretboard.

Since you've set your baseline at supporting Emacs 28, you could build a slick interface for this via transient.el.
The header-line-format of the buffer could be used to display the current settings of the fretboard as well.

**Comment by vifon** [comment]
I considered it. For now I think the current format strikes the best balance between flexibility and development complexity. It's simple and it works. I'll leave this issue open as someone else might want to invest time into it. Possibly the future me.
